# Generated by Django 4.2.7 on 2026-04-03 19:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


def backfill_admission_ward_stays(apps, schema_editor):
    Admission = apps.get_model('hospital', 'Admission')
    AdmissionWardStay = apps.get_model('hospital', 'AdmissionWardStay')
    for a in Admission.objects.filter(is_deleted=False).iterator():
        if not a.ward_id:
            continue
        if AdmissionWardStay.objects.filter(admission_id=a.pk, is_deleted=False).exists():
            continue
        ended = None if a.status == 'admitted' else a.discharge_date
        AdmissionWardStay.objects.create(
            admission_id=a.pk,
            ward_id=a.ward_id,
            bed_id=a.bed_id,
            started_at=a.admit_date,
            ended_at=ended,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1115_encounter_prefilled_context_last_edited_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionWardStay',
            fields=[
                (
                    'created',
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='created',
                    ),
                ),
                (
                    'modified',
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name='modified',
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('is_deleted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField()),
                (
                    'ended_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='Null while this is the current ward; set when patient transfers or is discharged.',
                        null=True,
                    ),
                ),
                (
                    'admission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ward_stays',
                        to='hospital.admission',
                    ),
                ),
                (
                    'bed',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='admission_stays',
                        to='hospital.bed',
                    ),
                ),
                (
                    'ward',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='admission_stays',
                        to='hospital.ward',
                    ),
                ),
            ],
            options={
                'ordering': ['started_at', 'id'],
            },
        ),
        migrations.RunPython(backfill_admission_ward_stays, noop_reverse),
    ]
