# Generated by Django 4.2.7 on 2026-04-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1116_admission_ward_stay'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_deleted', 'created'], name='patient_list_created_idx'),
        ),
    ]
