# Generated by Django 4.2.7 on 2026-04-07 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1117_patient_list_created_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyStockLoss',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('loss_type', models.CharField(choices=[('breakage', 'Breakage / spillage'), ('expiry', 'Expired — removed from saleable stock'), ('damage', 'Damaged packaging / suspected contamination'), ('theft_suspected', 'Theft / unaccounted loss'), ('recall', 'Manufacturer / regulatory recall'), ('other', 'Other (explain in notes)')], max_length=32)),
                ('quantity', models.PositiveIntegerField()),
                ('disposal_method', models.CharField(choices=[('medical_waste', 'Segregated pharmaceutical / medical waste'), ('incineration', 'Authorized incineration or destruction service'), ('supplier_return', 'Returned to supplier'), ('documented', 'Documented on-site destruction (witnessed)'), ('other', 'Other (see notes)')], max_length=32)),
                ('witness_name', models.CharField(blank=True, help_text='Second staff member present for segregation or destruction, if applicable', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Brief factual narrative (what, when observed, batch handling)')),
                ('pharmacy_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loss_records', to='hospital.pharmacystock')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_stock_losses_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacy stock loss / write-off',
                'verbose_name_plural': 'Pharmacy stock losses / write-offs',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacystockloss',
            index=models.Index(fields=['pharmacy_stock', '-created'], name='hospital_ph_pharmac_347ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacystockloss',
            index=models.Index(fields=['loss_type', '-created'], name='hospital_ph_loss_ty_16c3d5_idx'),
        ),
    ]
