# Generated by Django 4.2.7 on 2026-04-15 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1120_cashier_quick_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='preferred_supplier',
            field=models.ForeignKey(
                blank=True,
                help_text='Default supplier for this formulary item (accounts / procurement cross-reference)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='formulary_drugs',
                to='hospital.supplier',
            ),
        ),
    ]
