# Generated by Django 4.2.7 on 2026-04-17 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '1122_pharmacystock_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayableLine',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entry_type', models.CharField(choices=[('stock_receipt', 'Stock receipt'), ('manual_payable', 'Manual payable / invoice'), ('payment', 'Payment'), ('adjustment', 'Adjustment')], db_index=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive increases balance owed; negative records payment.', max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, help_text='Invoice #, cheque #, or other reference', max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payable_lines_created', to=settings.AUTH_USER_MODEL)),
                ('lab_reagent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payable_line', to='hospital.labreagent')),
                ('pharmacy_stock', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payable_line', to='hospital.pharmacystock')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_lines', to='hospital.supplier')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='supplierpayableline',
            index=models.Index(fields=['supplier', 'is_deleted'], name='hospital_su_supplie_f9fac0_idx'),
        ),
    ]
