# Generated by Django 4.2.7 on 2026-06-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1130_inventory_gl_posting_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='exclude_from_insurance',
            field=models.BooleanField(
                default=False,
                help_text='When set, insurance/corporate patients must pay cash for this drug at the cashier',
            ),
        ),
        migrations.AddField(
            model_name='drug',
            name='insurance_exclusion_reason',
            field=models.CharField(
                blank=True,
                help_text='Reason shown to pharmacy and cashier when this drug is insurance-excluded',
                max_length=255,
            ),
        ),
    ]
