# Generated by Django 4.2.7 on 2026-06-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1131_drug_insurance_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='exclude_from_insurance',
            field=models.BooleanField(
                default=False,
                help_text='When set, insurance/corporate patients must pay cash for this lab test at the cashier',
            ),
        ),
        migrations.AddField(
            model_name='labtest',
            name='insurance_exclusion_reason',
            field=models.CharField(
                blank=True,
                help_text='Reason shown to prescribers, lab and cashier when this test is insurance-excluded',
                max_length=255,
            ),
        ),
    ]
