# Generated by Django 4.2.7 on 2026-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1132_labtest_insurance_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='is_start_dose',
            field=models.BooleanField(
                default=False,
                help_text='Release to pharmacy before consultation is completed (initial/stat dose).',
            ),
        ),
    ]
