# Generated by Django 4.2.7 on 2026-07-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '1135_order_clinical_indication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingpayroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('pending_approval', 'Pending administrator approval'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashierquickservice',
            name='amount_corporate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Corporate patient price. Leave blank to use the insurance amount for corporate payers (same as built-in catalogue).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='exclude_from_insurance',
            field=models.BooleanField(default=False, help_text='When set, insurance patients must pay cash for this drug at the cashier (corporate billing unchanged)'),
        ),
        migrations.AlterField(
            model_name='hospitalsettings',
            name='backup_retention_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Keep backups for this many days (0 = no auto cleanup).'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='exclude_from_insurance',
            field=models.BooleanField(default=False, help_text='When set, insurance patients must pay cash for this lab test at the cashier (corporate billing unchanged)'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('lab_result', 'Lab Result'), ('imaging', 'Imaging Report'), ('prescription', 'Prescription'), ('otc', 'OTC Pharmacy'), ('discharge_summary', 'Discharge Summary'), ('consultation_note', 'Consultation Note'), ('surgical_report', 'Surgical Report'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='service_type',
            field=models.CharField(blank=True, choices=[('lab', 'Laboratory Test'), ('lab_test', 'Laboratory Test (order)'), ('lab_result', 'Laboratory Result'), ('pharmacy', 'Pharmacy/Medication'), ('pharmacy_prescription', 'Pharmacy Prescription'), ('pharmacy_walkin', 'Walk-in Pharmacy Sale'), ('medication', 'Medication Sale'), ('imaging', 'Imaging/Radiology'), ('imaging_study', 'Imaging Study'), ('consultation', 'Consultation'), ('gynecology', 'Gynecology / ANC'), ('admission', 'Admission'), ('detainment', 'Detainment'), ('bed', 'Bed / accommodation'), ('procedure', 'Procedure'), ('consumables', 'Clinical Consumables'), ('combined', 'Combined Services'), ('general', 'General / accounting sync'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('checked_in', '✅ Checked In - Waiting'), ('called', '📢 Called - Please Proceed'), ('vitals_completed', '🩺 Vitals Done - Awaiting Consultation'), ('in_progress', '👨\u200d⚕️ In Consultation'), ('completed', '✓ Completed'), ('no_show', '❌ No Show'), ('cancelled', '🚫 Cancelled')], default='checked_in', max_length=20),
        ),
    ]
